name: '<name>'
description: '<description>'
inputs:
  repo_token:  # id of input
    description: 'Github Token'
    required: true
  owner:  # id of input
    description: 'Github user or Organisation'
    required: true
  repo:  # id of input
    description: 'Github repo name'
    required: true
outputs:
  status: # id of output
    description: 'The http reponse code'
runs:
  using: 'node16'
  main: '../dist/<action>/index.js'
