name: 'Import ADO repo'
description: 'Import a repository from ADO'
inputs:
  repo_token:  # id of input
    description: 'Github Token'
    required: true
  owner:  # id of input
    description: 'Github user or Organisation'
    required: true
  repo:  # id of input
    description: 'Github repo name'
    required: true
  ado_repo:  # id of input
    description: 'The ADO repo to migrate'
    required: true
    default: 'https://accapplications@dev.azure.com/accapplications/tohutohu/_git/github-integration-tool'
  ado_user:  # id of input
    description: 'ADO user'
    required: true
  ado_pat:  # id of input
    description: 'ADO PAT'
    required: true
outputs:
  status: # id of output
    description: 'The status of the migration'
runs:
  using: 'node16'
  main: '../dist/repos-import/index.js'
