on: 
  workflow_dispatch:

# on: [push]

jobs:
  source_migrate:
    runs-on: ubuntu-latest
    name: ADO repo import
    steps:
      - name: Import repo step
        id: import
        uses: extravio/github-actions-acc@develop
        with:
          repo_token: ${{ secrets.JS_TOKEN }}
          owner: extravio
          repo: import-ado
          ado_repo: 'https://accapplications@dev.azure.com/accapplications/tohutohu/_git/github-integration-tool'
          ado_user: 'mikael.mrozik@acc.co.nz'
          ado_pat:  ${{ secrets.ADO_PAT }}
      # Use the output from the `import` step
      - name: Get the status
        run: echo "The status has started. The status is ${{ steps.import.outputs.status }}"