name: "Import ADO repo"

on: 
  workflow_dispatch:
  push:
    branches:
      - 'develop'

# on: [push]

jobs:
  source_migrate:
    runs-on: ubuntu-latest
    name: ADO repo import
    steps:
      # Create the repo
      - name: Create repo
        id: create
        uses: extravio/github-actions-acc/action-repos-create@develop
        with:
          repo_token: ${{ secrets.JS_TOKEN }}
          owner: extravio
          repo: import-ado
      # Use the output from the `import` step
      - name: Get the status
        run: echo "The reponse code is ${{ steps.import.outputs.status }}"

      # Import the repo from ADO
      - name: Import repo step
        id: import
        uses: extravio/github-actions-acc/action-repos-import@develop
        with:
          repo_token: ${{ secrets.JS_TOKEN }}
          owner: extravio
          repo: import-ado
          ado_repo: 'https://accapplications@dev.azure.com/accapplications/tohutohu/_git/github-integration-tool'
          ado_user: 'mikael.mrozik@acc.co.nz'
          ado_pat:  ${{ secrets.ADO_PAT }}
          
      # Use the output from the `import` step
      - name: Get the status
        run: echo "The status has started. The status is ${{ steps.import.outputs.status }}"