name: "Create a repo"

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'develop'

# on: [push]

jobs:
  source_migrate:
    runs-on: ubuntu-latest
    name: repos create
    steps:
      - name: Create repo
        id: create
        uses: extravio/github-actions-acc/action-repos-create@develop
        with:
          repo_token: ${{ secrets.JS_TOKEN }}
          owner: extravio
          repo: import-ado
      # Use the output from the `import` step
      - name: Get the status
        run: echo "The reponse code is ${{ steps.create.outputs.status }}"